main: com.drcnetwork.inventorytweak.ItemsGUI
author: Reynout123
version: 1.0
name: ItemsGUI
commands:
  gm1:
    description: Opens inventory
    usage: /gm1
  gmc:
    description: Opens inventory
    usage: /gmc
